name: "Pipeline Test"

on:
  push:
    branches:
      - main
  #pull_request:
  #  types: [opened, reopened]
  workflow_dispatch:
    inputs:
      action:
        required: true
        description: 'Terraform Action'
        default: 'plan'
        type: choice
        options:
          - plan
          - deploy
          - destroy
      terraform_version:
        required: true
        description: 'Terraform Version'
        default: '1.5.0'
        type: string
      environment:
        required: true
        description: 'Pipeline Environment'
        default: 'staging'
        type: choice
        options:
          - staging
          - dev
          - prod

jobs:
  terraform:
    uses: leandromoreirati/github-workflow/.github/workflows/terraform.yaml@main
    with:
      terraform_version: ${{ github.event.inputs.terraform_version }}
      environment: ${{ github.event.inputs.environment }}
      runs-on: 'ubuntu-latest'
      action: ${{ github.event.inputs.action }}
    #secrets:
    #  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
    #  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
    #  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
    #  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
    #  ARM_SECRET_ID: ${{ secrets.ARM_SECRET_ID }}
    secrets: inherit
    permissions:
      contents: read