run-name: 'Pre-Commit'

on:
  #push:
  #  branches:
  #    - feature/*
  #pull_request:
  #  types: [opened, reopened]
  workflow_dispatch:

jobs:
  pre-commit:
    uses: leandromoreirati/github-workflow/.github/workflows/precommit.yaml@main
    with:
      tag: 'latest'
      image: 'ghcr.io/antonbabenko/pre-commit-terraform'
      runs-on: 'ubuntu-latest'
    #secrets:
    #  envPAT: ${{ secrets.envPAT }}