run-name: 'Release'

on:
  push:
    branches:
      - main
      - feature/*
  #workflow_dispatch:

jobs:
  release:
    uses: leandromoreirati/github-workflow/.github/workflows/release.yaml@main
    with:
      versionSpec: '6.x'
      configFilePath: './GitVersion.yml'
      dotNetVersion: '3.1.x'
      runs-on: 'ubuntu-latest'
      environment: ''
    #secrets:
    #  envPAT: ${{ secrets.envPAT }}