name: "Sonar Scan"

on:
  push:
    branches:
      - main
      - feature/*
  workflow_dispatch:
    inputs:
      sonar_version:
        required: false
        description: 'Github Action Sonar Version'
        default: 'master'
        type: string
      runs-on:
        required: false
        description: 'Github Runner'
        default: 'ubuntu-latest'
        type: string
      organization:
        required: false
        description: 'Github Organization Owner'
        default: 'leandromoreirati'
        type: string
      project_key:
        required: false
        description: 'Github Repository Name'
        default: 'pipeline-test'
        type: string
      branch_name:
        required: false
        description: 'Github Repository Name'
        default: 'pipeline-test'
        type: string

jobs:
  release:
    uses: leandromoreirati/github-workflow/.github/workflows/sonar.yaml@main
    with:
      runs-on: 'ubuntu-latest'
      sonar_version: ${{ github.event.inputs.sonar_version }}
      organization: 'leandromoreirati'
      project_key: 'pipeline-test'
      branch_name: 'main'
    secrets: inherit