name: "Sonar Scan"

on:
  push:
    branches:
      - main
      - feature/*
  #workflow_dispatch:
  #  inputs:
  #    sonar_version:
  #      required: false
  #      description: 'Github Action Sonar Version'
  #      type: string
  #      default: 'master'
  #    runs-on:
  #      required: false
  #      description: 'Github Runner'
  #      type: string
  #      default: 'ubuntu-latest'
  #    organization:
  #      required: false
  #      description: 'Github Organization Owner'
  #      type: string
  #      default: 'leandromoreirati'
  #    project_key:
  #      required: false
  #      description: 'Github Repository Name'
  #      type: string
  #      default: 'pipeline-test'

jobs:
  release:
    uses: leandromoreirati/github-workflow/.github/workflows/sonar.yaml@main
    with:
      runs-on: 'ubuntu-latest'
      sonar_version: 'master'
      organization: 'leandromoreirati'
      project_key: 'pipeline-test'
    secrets: inherit