run-name: 'Sonar Scan'

on:
  push:
    branches:
      #- main
      - feature/**
  workflow_dispatch:
    inputs:
      runs-on:
        required: false
        description: 'Github Runner'
        type: string
        default: 'ubuntu-latest'
      organization:
        required: false
        description: 'Github Organization Owner'
        type: string
        default: 'leandromoreirati'
      project_key:
        required: false
        description: 'Github Repository Name'
        type: string
        default: 'pipeline-test'

jobs:
  release:
    uses: leandromoreirati/github-workflow/.github/workflows/sonar.yaml@main
    with:
      runs-on: 'ubuntu-latest'
      organization: 'leandromoreirati'
      project_key: 'pipeline-test'
    secrets: inherit